//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HL2Customizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resfile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resfile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HL2Customizer.Resources.resfile", typeof(resfile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap applyButton {
            get {
                object obj = ResourceManager.GetObject("applyButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] autoexec {
            get {
                object obj = ResourceManager.GetObject("autoexec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] clientscheme {
            get {
                object obj = ResourceManager.GetObject("clientscheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deleteIcon {
            get {
                object obj = ResourceManager.GetObject("deleteIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DSP preset definition file.
        ///
        ////////////////////////////////////////
        ///// WARNING: do not edit this file! //
        ////////////////////////////////////////
        ///
        ///// console &quot;dsp_reload&quot; reloads while engine running
        ///
        ///// PROCESSOR TYPE:
        /////  NULL			0		// pass through - must be 0
        /////  DLY				1		// simple feedback reverb
        /////  RVA				2		// parallel reverbs
        /////  FLT				3		// lowpass or highpass filter
        /////  CRS				4		// chorus					NOT TESTED
        /////  PTC				5		// pitch shifter			NOT TESTED (UPDATE: DOES NOT INTEGRATE WITH NE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dsp_presets {
            get {
                return ResourceManager.GetString("dsp_presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Example {
            get {
                object obj = ResourceManager.GetObject("Example", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon hl2c {
            get {
                object obj = ResourceManager.GetObject("hl2c", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HLogo {
            get {
                object obj = ResourceManager.GetObject("HLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // sample animation script
        /////
        /////
        ///// commands:
        /////	Animate &lt;panel name&gt; &lt;variable&gt; &lt;target value&gt; &lt;interpolator&gt; &lt;start time&gt; &lt;duration&gt;
        /////		variables:
        /////			FgColor
        /////			BgColor
        /////			Position
        /////			Size
        /////			Blur		(hud panels only)
        /////			TextColor	(hud panels only)
        /////			Ammo2Color	(hud panels only)
        /////			Alpha		(hud weapon selection only)
        /////			SelectionAlpha  (hud weapon selection only)
        /////			TextScan	(hud weapon selection only)
        /////
        /////		interpolator:
        /////			Linear
        /////			Accel - starts moving slow,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hudanimations {
            get {
                return ResourceManager.GetString("hudanimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] hudlayout {
            get {
                object obj = ResourceManager.GetObject("hudlayout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ScoreBoard {
            get {
                object obj = ResourceManager.GetObject("ScoreBoard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sourcescheme {
            get {
                object obj = ResourceManager.GetObject("sourcescheme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.4.4.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XHAIR {
            get {
                object obj = ResourceManager.GetObject("XHAIR", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
